
/*ALCANCE*/

INSERT INTO TIPO_REQUISITO VALUES (1,'Deseable'),(2,'Exigible');

INSERT INTO PRIORIDAD_REQUISITO VALUES (1,'Baja'),(2,'Media'),(3,'Alta');

INSERT INTO ESTADO_EDT VALUES (1,'Aprobado'),(2,'Pendiente'),(3,'Rechazado'),(4,'Eliminado');

INSERT INTO ESTADO_ALCANCE VALUES (1,'Pendiente'),(2,'Revisado'),(3,'Aceptado'),(4,'Aprobado');

INSERT INTO ESTADO_REQUISITO VALUES (1,'Aprobado'),(2,'Eliminado'),(3,'Aceptado'),(4,'Revisado'),(5,'Validado');

INSERT INTO CATEGORIA_REQUISITO VALUES (1,'Organizacional'),(2,'Funcional'),(3,'Entrega'),(4,'GestiÃ³n'),(5,'Proyecto'),(6,'Proceso'),(7,'Producto');

INSERT INTO ESTADO_ER VALUES (1,'Aprobado'),(2,'Rechazado');

/*RIESGOS*/
INSERT INTO `RIESGO_COMUN` VALUES (1,'Caida del repositorio',40,60,NULL,0),(2,'El encargado del proyecto se retira del equipo',10,90,NULL,0),(3,'Se levantó mal los requerimientos del sistema',30,80,NULL,0),(4,'El sector economico donde se ubica el proyecto ha crecido',80,40,NULL,1),(5,'Aumento del presupuesto asignado',23,70,NULL,1),(6,'El proyecto tiene un impacto positivo en los usuarios',50,90,NULL,1);

/*GENERAL*/
INSERT INTO ROL_EMPLEADO VALUES (1,'GERENTE DE PORTAFOLIO','GERENTE'),(2,'JEFE DE PROYECTO','JEFE'),(3,'MEMBRO DE EQUIPO','MIEMBRO');

INSERT INTO PROFESION VALUES 
(1,'CURIOSO'),
(2,'ANALISTA'),
(3,'DESARROLLADOR'),
(4,'CONSULTOR'),
(5,'MIL OFICIOS');

/*INSERT INTO EMPLEADO VALUES (1,'Oscar','Garay',null,null,'Oscar Garay',1000,1,'ACTIVO');

INSERT INTO SEGURIDAD values (1,'admin','admin',1,null,1);*/

INSERT INTO CATEGORIA_LEC_APRENDIDA VALUES (1,'INTEGRACION','DESC INT'),(2,'ALCANCE','DESC ALC'),
(3,'TIEMPOS','DESC TIEMPOS'),(4,'RIESGOS','DESC RIESGOS'),(5,'COSTOS','DESC COSTOS');

INSERT INTO PRIORIDAD_PROYECTO VALUES (1,'ESTRATEGICO'),(2,'ALTO POTENCIAL'),(3,'CLAVE PARA OPERAR'),(4,'SOPORTE');

INSERT INTO TIPO_PROYECTO VALUES (1,'PEQUEÑO'),(2,'MEDIANO'),(3,'GRANDE');

/*CRONOGRAMA*/

/*COSTOS*/
INSERT INTO UNIDAD_MEDIDA VALUES (1,'KG','KILOGRAMOS'),(2,'HH','HORAS HOMBRE'),(3,'UN','UNIDAD');

INSERT INTO INFLACION VALUES (2011,5),(2012,4),(2013,4.5),(2014,4.5),(2015,5);

INSERT INTO TIPO_COSTO VALUES (1,'COSTO DIRECTO'),(2,'COSTO INDIRECTO'),(3,'COSTO_HUNDIDO');

INSERT INTO INDICADOR VALUES (1, 'PV'),(2,'EV'),(3,'AC'),(4,'CV'),(5,'CPI'),(6,'SPI'),(7,'SV'),(8,'BAC'),(9,'EAC'),(10,'ETC'),(11,'VAC'),(12,'TCPI');

INSERT INTO ASIENTO_CONTABLE VALUES
(1,'MERCADERÍAS'),
(2,'PRODUCTOS TERMINADOS'),
(3,'INVERSIONES INMOBILIARIAS'),
(4,'REMUNERACIONES Y PARTICIPACIONES POR PAGAR'),
(5,'SUBPRODUCTOS, DESECHOS Y DESPERDICIOS'),
(6,'PRODUCTOS EN PROCESO'),
(7,'INMUEBLES, MAQUINARIA Y EQUIPO'),
(8,'MATERIAS PRIMAS'),
(9,'INTANGIBLES'),
(10,'MATERIALES AUXILIARES, SUMINISTROS Y REPUESTOS'),
(11,'ACTIVOS BIOLÓGICOS'),
(12,'OBLIGACIONES FINANCIERAS'),
(13,'ENVASES Y EMBALAJES'),
(14,'PROVISIONES'),
(15,'RESERVAS');

INSERT INTO CAMBIO_MONEDA VALUES (1,'NUEVOS SOLES'),(2,'DOLARES'),(3,'EUROS');

INSERT INTO CAMBIO_HISTORICO VALUES (1,SYSDATE(),1,1);
INSERT INTO CAMBIO_HISTORICO VALUES (2,SYSDATE(),2.8,1/2.8);
INSERT INTO CAMBIO_HISTORICO VALUES (3,SYSDATE(),3.4,1/3.4);

INSERT INTO CAMBIO_HISTORICO VALUES (1,DATE_ADD(SYSDATE(),INTERVAL 1 DAY),1,1);
INSERT INTO CAMBIO_HISTORICO VALUES (2,DATE_ADD(SYSDATE(),INTERVAL 1 DAY),2.8,1/2.8);
INSERT INTO CAMBIO_HISTORICO VALUES (3,DATE_ADD(SYSDATE(),INTERVAL 1 DAY),3.4,1/3.4);

INSERT INTO CAMBIO_HISTORICO VALUES (1,DATE_ADD(SYSDATE(),INTERVAL 2 DAY),1,1);
INSERT INTO CAMBIO_HISTORICO VALUES (2,DATE_ADD(SYSDATE(),INTERVAL 2 DAY),2.8,1/2.8);
INSERT INTO CAMBIO_HISTORICO VALUES (3,DATE_ADD(SYSDATE(),INTERVAL 2 DAY),3.4,1/3.4);

INSERT INTO CAMBIO_HISTORICO VALUES (1,DATE_ADD(SYSDATE(),INTERVAL 3 DAY),1,1);
INSERT INTO CAMBIO_HISTORICO VALUES (2,DATE_ADD(SYSDATE(),INTERVAL 3 DAY),2.8,1/2.8);
INSERT INTO CAMBIO_HISTORICO VALUES (3,DATE_ADD(SYSDATE(),INTERVAL 3 DAY),3.4,1/3.4);

INSERT INTO CAMBIO_HISTORICO VALUES (1,DATE_ADD(SYSDATE(),INTERVAL 4 DAY),1,1);
INSERT INTO CAMBIO_HISTORICO VALUES (2,DATE_ADD(SYSDATE(),INTERVAL 4 DAY),2.8,1/2.8);
INSERT INTO CAMBIO_HISTORICO VALUES (3,DATE_ADD(SYSDATE(),INTERVAL 4 DAY),3.4,1/3.4);

